@extends('/admin')

@section('content')
    <div class="report-container">
        <header>
            <h1>Chicken and Cage Details Report</h1>
            <p><strong>Date:</strong> {{ date('Y-m-d') }}</p>
        </header>

        <section class="report-summary" style="margin-left: 150px">
            <h2>Objective</h2>
            <p>Provide detailed information about the chickens, their breeds, and the cages they are housed in.</p>
        </section>

       

        <section class="report-chart" style="text-align: center;">
            <h2>Cage Age Group Distribution</h2>
            <div class="chart-container">
                <canvas id="cageAgeGroupChart"></canvas>
            </div>
        </section>

        <footer>
            <p>Report generated by: <strong>Admin</strong></p>
            <p><strong>Date:</strong> {{ date('Y-m-d') }}</p>
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        const ctx = document.getElementById('cageAgeGroupChart').getContext('2d');
        
        // Hardcoded data for multiple cages
        const labels = ['Cage 1', 'Cage 2']; // Add more cage labels as needed
        const youngData = [2, 0]; // Number of young chickens per cage
        const middleAgedData = [1, 0]; // Number of middle-aged chickens per cage
        const oldData = [0, 1]; // Number of old chickens per cage
        const adultData = [0, 1]; // Number of adult chickens per cage

        const cageAgeGroupChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: labels,
                datasets: [
                    {
                        label: 'Young (0-6 weeks)',
                        data: youngData,
                        backgroundColor: 'rgba(75, 192, 192, 0.2)',
                        borderColor: 'rgba(75, 192, 192, 1)',
                        borderWidth: 1
                    },
                    {
                        label: 'Middle-aged (7-12 weeks)',
                        data: middleAgedData,
                        backgroundColor: 'rgba(54, 162, 235, 0.2)',
                        borderColor: 'rgba(54, 162, 235, 1)',
                        borderWidth: 1
                    },
                    {
                        label: 'Old (13-20 weeks)',
                        data: oldData,
                        backgroundColor: 'rgba(255, 206, 86, 0.2)',
                        borderColor: 'rgba(255, 206, 86, 1)',
                        borderWidth: 1
                    },
                    {
                        label: 'Adult (20+ weeks)',
                        data: adultData,
                        backgroundColor: 'rgba(255, 99, 132, 0.2)',
                        borderColor: 'rgba(255, 99, 132, 1)',
                        borderWidth: 1
                    }
                ]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>

<section class="report-details" style="text-align: center;">
    <h2>Details Report</h2>
    <div style="display: inline-block;">
        <table border="1" class="table">
            <thead>
                <tr>
                    
                    <th>Cage Name</th>
                    <th>Size</th>
                    <th>Capacity</th>
                    <th>Type</th>
                   
                    <th>Breed Name</th>
                    <th>Gender</th>
                    <th>Origin</th>
                    <th>Date of Birth</th>
                    <th>Age Group</th>
                </tr>
            </thead>
            <tbody>
                <!-- Cage 1 -->
                <tr>
                    
                    <td>Cage 1</td>
                    <td>Large</td>
                    <td>50</td>
                    <td>Type A</td>
                    
                    <td>Breed 1</td>
                    <td>Female</td>
                    <td>Country A</td>
                    <td>2024-06-15</td>
                    <td>Young (0-6 weeks)</td>
                </tr>
                <tr>
                    
                    <td>Cage 1</td>
                    <td>Large</td>
                    <td>50</td>
                    <td>Type A</td>
                   
                    <td>Breed 2</td>
                    <td>Male</td>
                    <td>Country B</td>
                    <td>2024-05-01</td>
                    <td>Middle-aged (7-12 weeks)</td>
                </tr>
                <!-- Cage 2 -->
                <tr>
                    
                    <td>Cage 2</td>
                    <td>Medium</td>
                    <td>30</td>
                    <td>Type B</td>
                    
                    <td>Breed 3</td>
                    <td>Female</td>
                    <td>Country C</td>
                    <td>2024-03-15</td>
                    <td>Old (13-20 weeks)</td>
                </tr>
                <tr>
                    
                    <td>Cage 2</td>
                    <td>Medium</td>
                    <td>30</td>
                    <td>Type B</td>
                   
                    <td>Breed 4</td>
                    <td>Male</td>
                    <td>Country D</td>
                    <td>2024-01-10</td>
                    <td>Adult (20+ weeks)</td>
                </tr>
                <!-- Add more cages here as needed -->
            </tbody>
        </table>
    </div>
</section>

    <style>
        .report-container {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        header, footer {
            text-align: center;
            margin-bottom: 20px;
        }

        h1, h2 {
            color: #333;
        }

        .report-summary, .report-details, .report-chart {
            margin-bottom: 20px;
        }

        .table {
            border-collapse: collapse;
            margin: 20px 0;
            width: 100%;
        }

        .table th, .table td {
            padding: 8px 12px;
            text-align: left;
        }

        .table th {
            background-color: #f2f2f2;
        }

        .report-chart {
            margin-top: 20px;
            text-align: center;
        }

        .chart-container {
            width: 80%;
            margin: 0 auto;
        }
    </style>
@endsection
