{{-- @extends('/admin')

@section('content') --}}
    {{-- <div class="report-container">
        <header>
            <h1>Summary Report</h1>
            <p><strong>Date:</strong> {{ date('Y-m-d') }}</p>
        </header>

        <section class="report-date-picker">
            <h2>Select Report Date</h2>
            {{-- action="{{ route('report.summary') }}"
            <form method="GET" >
                <label for="start-date">Start Date:</label>
                <input type="date" id="report-date" name="report_date" value="{{ request('report_date', date('Y-m-d')) }}">
                <label for="end-date">End Date:</label>
                <input type="date" id="report-end-date" name="endreport_date" value="{{ request('report_date', date('Y-m-d')) }}">
                <button type="submit">Generate Report</button>
            </form>
        </section>

        @if(isset($data))
            <section class="report-summary">
                <h2>Overview</h2>
                <p>This report provides a summary of key metrics related to the Poultry Egg Production Farm Management System. The data presented here offers insights into the system's performance and efficiency.</p>
            </section>

            <section class="report-table">
                <h2>Metrics Summary</h2>
                <table border="1" class="table">
                    <thead>
                        <tr>
                            <th>Metric</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($data['labels'] as $index => $label)
                            <tr>
                                <td>{{ $label }}</td>
                                <td>{{ $data['values'][$index] }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </section>

            <section class="report-chart">
                <h2>Visual Representation</h2>
                <canvas id="summaryChart"></canvas>
            </section>
        @endif

        <footer>
            <p>Report generated by: <strong>Admin</strong></p>
            <p><strong>Date:</strong> {{ date('Y-m-d') }}</p>
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        @if(isset($data))
        const ctx = document.getElementById('summaryChart').getContext('2d');
        const summaryChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: @json($data['labels']),
                datasets: [{
                    label: 'Metrics',
                    data: @json($data['values']),
                    backgroundColor: 'rgba(75, 192, 192, 0.2)',
                    borderColor: 'rgba(75, 192, 192, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
        @endif
    </script>

    <style>
        .report-container {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        header, footer {
            text-align: center;
            margin-bottom: 20px;
        }

        h1, h2 {
            color: #333;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        .table th, .table td {
            padding: 8px 12px;
            text-align: left;
        }

        .table th {
            background-color: #f2f2f2;
        }

        .report-date-picker {
            margin-bottom: 20px;
        }

        .report-date-picker label {
            margin-right: 10px;
        }

        .report-date-picker button {
            padding: 6px 12px;
            background-color: #007bff;
            color: white;
            border: none;
            cursor: pointer;
        }

        .report-date-picker button:hover {
            background-color: #0056b3;
        }
    </style> --}}

    @extends('/admin')

    @section('content')
        <div class="report-container">
            <section class="report-date-picker" style="margin: 50px">
                <h2>Select Report Date</h2>
                {{-- action="{{ route('report.summary') }}"--}}
                <form method="GET" >
                    <label for="start-date">Start Date:</label>
                    <input type="date" id="report-date" name="report_date" value="{{ request('report_date', date('Y-m-d')) }}">
                    <label for="end-date">End Date:</label>
                    <input type="date" id="report-end-date" name="endreport_date" value="{{ request('report_date', date('Y-m-d')) }}">
                    <button type="submit">Generate Report</button>
                </form>
            </section>

            <section class="report-summary" style="margin: 50px">
                <h2>Objective</h2>
                <p>Provide an overview of the number of eggs categorized by their grade.</p>
            </section>
            <header>
                <h1>Egg Grading Summary Report</h1>
                <p><strong>Date:</strong> {{ date('Y-m-d') }}</p>
            </header>
    
           
    
            <section class="report-chart">
                <h2>Visual Representation</h2>
                <div class="chart-container">
                    <canvas id="eggChart"></canvas>
                </div>
            </section>
    
            <section class="report-details" style="text-align: center;">
                <h2>Summary Details</h2>
                <div style="display: inline-block;">
                    <table border="1" class="table">
                        <thead>
                            <tr>
                                <th>Grade</th>
                                <th>Description</th>
                                <th>Number of Eggs</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Grade AA</td>
                                <td>Highest quality with thick and firm whites and well-centered, high-standing yolks.</td>
                                <td>4,000</td>
                            </tr>
                            <tr>
                                <td>Grade A</td>
                                <td>Slightly lower in quality than Grade AA, with reasonably firm whites.</td>
                                <td>3,500</td>
                            </tr>
                            <tr>
                                <td>Grade B</td>
                                <td>Lowest grade, with thinner whites and flatter yolks. Suitable for baking and other uses where appearance is not critical.</td>
                                <td>2,500</td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th colspan="2">Total Eggs</th>
                                <th>10,000</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </section>
    
            <footer>
                <p>Report generated by: <strong>Admin</strong></p>
                <p><strong>Date:</strong> {{ date('Y-m-d') }}</p>
            </footer>
        </div>
    
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script>
            const ctx = document.getElementById('eggChart').getContext('2d');
            const eggChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: ['Grade AA', 'Grade A', 'Grade B'],
                    datasets: [{
                        label: 'Number of Eggs',
                        data: [4000, 3500, 2500],
                        backgroundColor: [
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)'
                        ],
                        borderColor: [
                            'rgba(75, 192, 192, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    plugins: {
                        legend: {
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'Egg Grading Distribution'
                        }
                    }
                },
            });
        </script>
    
        <style>
            .report-container {
                font-family: Arial, sans-serif;
                margin: 20px;
            }
    
            header, footer {
                text-align: center;
                margin-bottom: 20px;
            }
    
            h1, h2, h3 {
                color: #333;
            }
    
            .report-summary, .report-details {
                margin-bottom: 20px;
            }
    
            .table {
                border-collapse: collapse;
                margin: 20px 0;
                width: 100%;
            }
    
            .table th, .table td {
                padding: 8px 12px;
                text-align: left;
            }
    
            .table th {
                background-color: #f2f2f2;
            }
    
            .report-chart {
                margin-top: 20px;
                text-align: center;
            }
    
            .chart-container {
                width: 50%;
                margin: 0 auto;
            }

            
        .report-date-picker {
            margin-bottom: 20px;
        }

        .report-date-picker label {
            margin-right: 10px;
        }

        .report-date-picker button {
            padding: 6px 12px;
            background-color: #007bff;
            color: white;
            border: none;
            cursor: pointer;
        }

        .report-date-picker button:hover {
            background-color: #0056b3;
        }
        </style>
    @endsection
    
